### PR TITLE
Fix store typing

### LINKED ISSUE #160: Store constructor signature mismatches w/ type definition
On master branch, [src/store/Store.js](https://github.com/tshaddix/react-chrome-redux/blob/master/src/store/Store.js#L24) accepts `patchStrategy` optionally and rejects `diffStrategy`.
```js
constructor({portName, state = {}, extensionId = null, serializer = noop, deserializer = noop, patchStrategy = shallowDiff})
```
however, [index.d.ts](https://github.com/tshaddix/react-chrome-redux/blob/master/index.d.ts#L11) requires both `diffStrategy` and `patchStrategy`.

### PR DESCRIPTION
**Pull request by Yuiki**
Fix some typing for TypeScript
closes #160

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -80,7 +79,8 @@ export function wrapStore<S>(
     portName: string,
     dispatchResponder?(dispatchResult: any, send: (response: any) => void): void,
     serializer?: Function,
-    deserializer?: Function
+    deserializer?: Function,
+    diffStrategy?: Function
```
Comment (tshaddix) [inline index.d.ts]: Seems like we should assign this to the `DiffStrategy` type, correct?

Comment (Yuiki) [reply index.d.ts]: I see. You're right.

**Comment by tshaddix** [comment]
Released in `2.0.0-alpha.3`
